include: package:very_good_analysis/analysis_options.3.1.0.yaml
# include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**/**.g.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/**.freezed.dart"
    - "**.yaml"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    sort_constructors_first: false
    constant_identifier_names: false
    always_put_required_named_parameters_first: false
    prefer_single_quotes: true
    require_trailing_commas: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
