name: rest_custom_client
description: Cliente personalizado para peticiones http Rest.
version: 1.1.0+3
publish_to: none
repository: https://github.com/fardcrex/rest_custom_client

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.6.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logger: ^2.4.0
  path: ^1.8.3
  pretty_dio_logger: ^1.4.0
  regexpattern: ^2.6.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.24.4
  very_good_analysis: ^5.0.0+1
  build_runner: ^2.4.7

  freezed: ^2.4.1
  json_serializable: ^6.7.1
